version: '3'

services:
  physmus-client:
    container_name: physmus-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_STRAPI_API_URL: ${NEXT_PUBLIC_STRAPI_API_URL}
        NEXT_PUBLIC_STRAPI_DOMAIN: ${NEXT_PUBLIC_STRAPI_DOMAIN}
        REVALIDATE_TOKEN: ${REVALIDATE_TOKEN}
    restart: always
    volumes:
      - client_next_cache_physmus:/app/.next/cache
    ports:
      - 3000:3000
    networks:
      - physmus-net

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  physmus-net:
    name: physmus-net
    external: true

volumes:
  client_next_cache_physmus:
    external: true