import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import { Footer } from "@/components/footer";


const montserrat = Montserrat({
  weight: '400',
  display: 'swap',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Physmus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
      <Header/>
      <main>{children}</main>
      <Toaster />
      <Footer/>
      </body>
    </html>
  );
}
