import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Physmus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <Header />
      
      <main>{children}</main>
      </body>
    </html>
  );
}
